macbre/sql-metadata

Makefile
README.md
sql_metadata.py
test/test_query.py

Resolves #17
```python
>>> sql__metadata.get_query_tables("SELECT a.* FROM product_a.users AS a JOIN product_b.users AS b ON a.ip_address = b.ip_address")
['product_a.users', 'product_b.users']
```
and
```python
>>> sql_metadata.get_query_columns("SELECT a.* FROM product_a.users AS a JOIN product_b.users AS b ON a.ip_address = b.ip_address")
['a.*', 'a.ip_address', 'b.ip_address']
```

Add support for table schemas in get_query_tables()

---

sql_metadata.py
test/test_query.py

This PR adds support for parsing `database.schema.table` notation in get_query_tables which is supported by some databases including Snowflake.

get_query_tables: Add support for `database.schema.table` notation

---

sql_metadata.py
test/__init__.py
test/test_query.py

See https://github.com/macbre/index-digest/pull/171
```sql
SELECT s.cust_id,count(s.cust_id) FROM SH.sales s GROUP BY s.cust_id HAVING s.cust_id != '1660' AND s.cust_id != '2'
```
Gives `s.cust_id` as a table name instead of `SH.sales`.

Add test_query_with_having

---

README.md
sql_metadata.py
test/test_aliases.py
test/test_get_query_columns.py

```python
sql = "SELECT a.* FROM users1 AS a JOIN users2 AS b ON a.ip_address = b.ip_address"
get_query_columns(sql)  # should return ['users1.*', 'users1.ip_address', 'users2.ip_address']
```
And introduce `get_query_table_aliases`:
```python
>>> sql_metadata.get_query_table_aliases("SELECT test FROM foo AS f")
{'f': 'foo'}
```
Resolves #52
However the following aliases syntax is not yet supported (missing `AS` keyword):
```sql
SELECT foo FROM test t`
```

Resolve table aliases in get_query_columns

---

sql_metadata.py
test/test_query.py

Bug reported and fix suggested by Levent Koc
```python
assert get_query_columns(
'SELECT id FROM cm WHERE cm.status = 1 AND cm.OPERATIONDATE IS NULL AND cm.OID IN(123123);'
) == ['id', 'cm.status', 'cm.OPERATIONDATE', 'cm.OID']
```
Before the fix `cm.OID` was not among the returned columns.

get_query_columns: improve handling of queries with "IS NULL" conditions

---

sql_metadata.py
test/test_query.py

I have fixed issue with additional whitespaces in multiple word keywords (like GROUP BY, INNER JOIN etc) and also issue with queries with UNION

 Fixes macbre/sql-metadata#80; fixes macbre/sql-metadata#79

---

sql_metadata.py
test/test_hive.py
test/test_query.py

Partially covers #112 
`WITH` handling will be improved when a new tokens iterator is introduced - see #98

Improved brackets handling

---

sql_metadata/parser.py
test/test_getting_columns.py

Improved handling of custom SQL functions when getting the list of columns

---

README.md
sql_metadata/compat.py
sql_metadata/parser.py
test/test_compat.py

In order to make the introduction of sql-metadata v2.0 smoother a compatibility layer has been introduced. You can use it by simply changing the imports in your code:
```python
from sql_metadata import get_query_columns, get_query_tables
```
into:
```python
from sql_metadata.compat import get_query_columns, get_query_tables
```
The following functions are available in `sql_metadata.compat` module:
* `generalize_sql`
* `get_query_columns`
* `get_query_limit_and_offset`
* `get_query_tables`
* `get_query_tokens`
* `preprocess_query`
/cc @collerek

Introduce a compatibility layer for 1.x functions 

---

sql_metadata/parser.py
test/test_create_table.py

Add a support for CREATE TABLE queries

---

.github/workflows/python-ci.yml
README.md
pyproject.toml
sql_metadata/parser.py
sql_metadata/token.py
sql_metadata/utils.py
test/test_column_aliases.py
test/test_multiple_subqueries.py

Final piece of work in regard of resolving aliases and columns coming from sub-queries to the actual database columns.
Now all aliases should resolve and only real columns should be included in columns and columns_dict.
Following the updated readme note the tables in join:
```python
from sql_metadata import Parser
parser = Parser(
"""
SELECT COUNT(1) FROM
(SELECT std.task_id FROM some_task_detail std WHERE std.STATUS = 1) a
JOIN (SELECT st.task_id FROM some_task st WHERE task_type_id = 80) b
ON a.task_id = b.task_id;
"""
)
parser.subqueries
parser.subqueries_names
parser.columns
#["some_task_detail.task_id", "some_task_detail.STATUS", "some_task.task_id", 
parser.columns_dict
#{'join': ['some_task_detail.task_id', 'some_task.task_id'],
```
Let me know what you think :)

Resolving subqueries columns

---

.github/workflows/python-ci.yml
sql_metadata/parser.py
sql_metadata/token.py
test/test_create_table.py

Fix for create table with with clause

---

sql_metadata/parser.py
test/test_getting_tables.py
test/test_query_type.py
test/test_values.py

Fixes #163
```python
assert ["bar"] == Parser("/* foo */ INSERT IGNORE INTO bar VALUES (1, '123', '2017-01-01');").tables
```

Handle leading comments in queries

---

sql_metadata/parser.py
test/test_with_statements.py

Fixes the error from #161, as similar to create tables the condition for parentheses was oversimplified.
Note that this one still has error as we do not support lateral view explode keyword, but that should be fixed in a separate pr I guess. (you wanted smaller ones :) )

Fix parsing with clauses, fix for #161

---

.flake8
poetry.lock
pyproject.toml
sql_metadata/__init__.py
sql_metadata/compat.py
sql_metadata/generalizator.py
sql_metadata/keywords_lists.py
sql_metadata/parser.py
sql_metadata/token.py
test/test_aliases.py
test/test_column_aliases.py
test/test_comments.py
test/test_create_table.py
test/test_getting_columns.py
test/test_getting_tables.py
test/test_hive.py
test/test_limit_and_offset.py
test/test_mssql_server.py
test/test_multiple_subqueries.py
test/test_normalization.py
test/test_postgress.py
test/test_query.py
test/test_values.py
test/test_with_statements.py

Fix for from clause in extract function close: #186
Fix for wrong alias check, close #188
Some simplifications:
- Added `TokenType` enum and `token_type` to token and populate it with enum value
- Merged token values with tables and database delimiter into one token and removed left_expand token property
- Cleaned no longer required checks for `is_dot` property as there are no dot tokens anymore
- Moved populating `column_aliases_dict` dictionary to `column_aliases_names`
- Added flake8 to warn about complexity before CodeFactor - also split long string lines and remove trailing whitespace

Multi from aliases

---

.github/workflows/python-ci.yml

```
coveralls.exception.CoverallsException: Could not submit coverage: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs
```

Ignore failed coverage uploads to Coveralls

---

README.md

I've created a small demo site showcasing sql-metadata that you can checkout here: https://sql-app.infocruncher.com/
It's served by API Gateway and Lambda, code for it is available also: https://github.com/dylanhogg/sql-app
I thought it may be useful to include a reference to the demo from the README.

Add interactive demo link to README

---

sql_metadata/parser.py
sql_metadata/token.py
test/test_aliases.py
test/test_getting_tables.py

This PR tries to solve issue #277 
When checking if a token can be a potential table alias, I add non `AS` keyword as a valid table alias.
For a valid query like below (only Oracle consider `SYSTEM` as keyword according to this list, https://github.com/andialbrecht/sqlparse/blob/e66046785b816e5c2d22f101f36faefd19c4a771/sqlparse/keywords.py):
```SQL
SELECT system.id
FROM foo system
```
`parser.tables_aliases` will correctly return `{"system": "foo"}`
For Oracle, this query is probably invalid, this approach will still return the same table aliases, but I don't think this probably matters less comparing to not returning correct table aliases for even valid queries.
In the PR, I added a new member variable `is_as_keyword` to `Token`, and I found several places of code uses `token.normalized …

Allow using keyword as table alias

---

sql_metadata/keywords_lists.py
sql_metadata/parser.py
test/test_with_statements.py

Fix for https://github.com/macbre/sql-metadata/issues/309

Do not consider `AS (` from window clause as query start

---

.github/workflows/python-ci.yml

Otherwise we get:
```
Installing Poetry 👷
Retrieving Poetry metadata
This will download and install the latest version of Poetry,
a dependency and package manager for Python.
It will add the `poetry` command to Poetry's bin directory, located at:
/home/runner/.local/bin
You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.
Installing Poetry (1.2.0)
Installing Poetry (1.2.0): Creating environment
Installing Poetry (1.2.0): Installing Poetry
Installing Poetry (1.2.0): Creating script
Installing Poetry (1.2.0): Done
Poetry (1.2.0) is installed now. Great!
You can test that everything is set up by executing:
`poetry --version`
/home/runner/work/_actions/snok/install-poetry/v1.3/main.sh: line 33: poetry: command not found …
```

Force the Poetry version to 1.1.14

---

sql_metadata/parser.py
test/test_limit_and_offset.py

Fix handling of LIMIT / OFFSET in queries with the IN condition

---

sql_metadata/parser.py

See #423
`sql_metadata/parser.py:127:5: C901 'Parser.tokens' is too complex (9)`

Parser.tokens: ignore flake8 error

---

sql_metadata/parser.py
test/test_with_statements.py

There's popular DB ClickHouse (https://clickhouse.com/) which has specific syntax for With expressions. So there's available "identifier" syntax which works almost like variables but in SQL way. This syntax looks like a reversed ordinary CTE where calculable expression is set at the left part and its name at the right (https://clickhouse.com/docs/en/sql-reference/statements/select/with#examples).
Currently such syntax causes such an error on `tables` property call:
<details>
<summary>Traceback</summary>
```python
table_names = Parser(query).tables
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sql_metadata/parser.py", line 345, in tables
with_names = self.with_names
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sql_metadata/parser.py", line 463, in …
```

ClickHouse: improved tokens handling

---

sql_metadata/parser.py

redundant line of code as both cases get addressed using regex in line of code above the deleted

Update _preprocess_query function in  parser.py

---

sql_metadata/keywords_lists.py
sql_metadata/parser.py
test/test_query_type.py

Reference: https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateFunction

support hive create function

---

sql_metadata/token.py
test/test_column_aliases.py

For this SQL:
```SQL
SELECT A * B FROM C;
```
Was incorrectly parsed, columns=["A"], the right thing to do is ["A", "B"].

fix is_alias_without_as logical error

---

sql_metadata/parser.py
test/test_mssql_server.py

Resolves https://github.com/macbre/sql-metadata/issues/475

fixes issue 475 MSSQL Unqualified Schema Table Parsing

---

sql_metadata/parser.py
test/test_query_type.py

query_type: shorten the SQL query when logging the exception

---

sql_metadata/keywords_lists.py
test/test_getting_columns.py

Fix columns reading for queries with double INNER JOIN
