macbre/sql-metadata

- .gitignore
- .travis.yml
- Makefile
- README.md
- setup.py
- sql_metadata.py
- test/test_query.py
> Initial version

- setup.py
- sql_metadata.py
- test/test_query.py
> Parsing improved

- sql_metadata.py
- test/test_query.py
> Handle more complex SQL queries

- sql_metadata.py
- test/test_query.py
```sql
SELECT date_format(time_id,'%Y-%m-%d')  ...
```
> Handle more SQL functions (see #8)

- sql_metadata.py
- test/test_query.py
Will be used by https://github.com/macbre/index-digest/issues/118
> Introduce get_query_limit_and_offset()

- .gitignore
- README.md
- sql_metadata.py
- test/test_query.py
Will be used by https://github.com/macbre/index-digest/issues/125
> get_query_columns: add support for INSERT queries

- sql_metadata.py
- test/test_query.py
> Handle empty query argument of get_query_tokens

- Makefile
- test/test_query.py
> Tests refactoring

- sql_metadata.py
- test/test_query.py
> get_query_tables() breaks on INSERT INTO ... SELECT  … 

- README.md
- sql_metadata.py
- test/test_normalization.py
> Move normalize_sql to sql-metadata

- README.md
- sql_metadata.py
- test/test_hive.py
- test/test_query.py
> Handle Apache Hive queries

- .travis.yml
- setup.py
> Support Python 3.x only

- setup.py
- sql_metadata.py
https://github.com/andialbrecht/sqlparse/compare/0.2.4...0.3.1
> Update sqlparse dependency

- sql_metadata.py
- test/test_query.py
> preprocess_query: remove newlines

- sql_metadata.py
- test/test_query.py
> Improve JOINs support

- test/test_query.py
> test_redshift: add cases for ALTER TABLE x APPEND FROM y

- test/test_query.py
> test_sql_server_cte: add test cases

- .github/workflows/pythonapp.yml
See https://github.com/macbre/index-digest/pull/190
> CI: cache pip dependencies

- .github/workflows/black.yml
- README.md
- setup.py
- sql_metadata.py
- test/__init__.py
- test/test_aliases.py
- test/test_get_query_columns.py
- test/test_hive.py
- test/test_normalization.py
- test/test_query.py
https://pypi.org/project/black/
<a href="https://github.com/psf/black"><img alt="Code style: black" src="https://img.shields.io/badge/code%20style-black-000000.svg"></a>
> Install black code formatter

- sql_metadata.py
- test/test_query.py
> Make get_query_tables() case insensitive

- sql_metadata.py
- test/test_query.py
> Handle queries with DISTINCT / UNIQUE keyword

- .github/workflows/python-ci.yml
- pyproject.toml
And fix the way `venv` cache is handled
> Improve CI cache handling

- test/test_query.py
> Extend test coverage for UNION queries

- .github/workflows/python-ci.yml
See https://github.com/snok/install-poetry/pull/24
> Use snok/install-poetry@v1.1.2

- .github/workflows/auto-merge-dependabot.yml
https://stefanzweifel.io/posts/2021/04/28/auto-merge-dependabot-pull-requests/
Tested here - https://github.com/pigs-will-fly/py-xml-sitemap-writer/pull/32
> Automerge dependabot pull requests

- .github/workflows/python-ci.yml
- Makefile
- poetry.lock
- pyproject.toml
* https://coveralls.io/github/macbre/sql-metadata
* https://github.com/marketplace/actions/coveralls-python
----
[![Coverage Status](https://coveralls.io/repos/github/macbre/sql-metadata/badge.svg?branch=master)](https://coveralls.io/github/macbre/sql-metadata?branch=master)
> Upload coverage report to Coveralls

- sql_metadata/parser.py
- test/test_create_table.py
> Fix create schema

- .github/workflows/python-ci.yml
https://github.com/python-poetry/poetry/releases/tag/1.1.7
> CI - install Poetry 1.1.7

- .github/workflows/black.yml
Extract version from project dependencies
> CI - install the latest black version

- sql_metadata/parser.py
- sql_metadata/token.py
- test/test_mssql_server.py
- test/test_multiple_subqueries.py
Added code change and test.
Resolves #202
> Ignore case on column alias names from subquery

- test/test_column_aliases.py
Adds additional test case for #226 
The issue is already fixed on master but not releases, @macbre can we merge all those bug fixes and create a new release?
I guess we should release more often. the changes already merged into master..
Close: #226
> additional test for cast

- sql_metadata/parser.py
- test/test_query_type.py
> allow redundant parentheses around (sub)queries

- sql_metadata/parser.py
- sql_metadata/token.py
- test/test_create_table.py
> add support for create if not exists

- sql_metadata/parser.py
- sql_metadata/token.py
- test/test_getting_columns.py
> fix recurrent aliases names leading to infinite loop

- .github/workflows/auto-merge-dependabot.yml
- sql_metadata/keywords_lists.py
- sql_metadata/parser.py
- test/test_column_aliases.py
- test/test_getting_columns.py
https://www.geeksforgeeks.org/sql-using-clause/
https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqljusing.html
UPDATE: Also fixed to specifically not count `USING` when doing `CONVERT(somecol USING utf8)`
> Add `USING` to column keywords

- sql_metadata/keywords_lists.py
- test/test_query_type.py
Everything seems to work fine after that even with some quite complex queries.
> Adds DELETE as a supported query type

- sql_metadata/keywords_lists.py
- sql_metadata/parser.py
- test/test_drop_table.py
- test/test_query_type.py
> Add a support for DROP TABLE queries

- .github/workflows/python-ci.yml
```yaml
strategy:
fail-fast: false
```
> CI - try to test against all Python versions

- sql_metadata/parser.py
- test/test_getting_tables.py
> Properly support upsert queries when extracting table names

- test/test_sqlite.py
> Add a test coverage for the NATURAL JOIN

- sql_metadata/keywords_lists.py
- test/test_alter.py
And add some coverage for the `ALTER TABLE` queries.
Resolves #542.
> Fix handling of the `ALTER TABLE ... ADD KEY` queries
